{% set name = "pyFFTW" %}
{% set version = "0.12.0" %}
{% set sha256 = "60988e823ca75808a26fd79d88dbae1de3699e72a293f812aa4534f8a0a58cb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}
    # only need fftw at run-time if static linking was not used
    - fftw  # [win]


about:
  home: http://hgomersall.github.com/pyFFTW/
  license: BSD or GPL 2
  license_file: LICENSE.txt
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.

extra:
  recipe-maintainers:
    - grlee77
    - hgomersall
    - jakirkham
    - jjhelmus
    - beckermr
