{% set name = "pyFFTW" %}
{% set version = "0.14.0" %}
{% set sha256 = "a55f94d3da9b5c04de1bc96932a93f922910f3984557931356173a515277b65b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no-system-include.patch

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython >=3
    - python
    - pip
    - numpy
    - fftw  # [win]
    - fftw-static  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}


about:
  home: http://hgomersall.github.com/pyFFTW/
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.

extra:
  recipe-maintainers:
    - grlee77
    - hgomersall
    - jakirkham
    - paugier
