{% set name = "pyFFTW" %}
{% set version = "0.13.0" %}
{% set sha256 = "60988e823ca75808a26fd79d88dbae1de3699e72a293f812aa4534f8a0a58cb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  git_url: https://github.com/JeppeKlitgaard/pyFFTW.git
  git_rev: cibuildwheel
  sha256: {{ sha256 }}

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}
    # only need fftw at run-time if static linking was not used
    - fftw


about:
  home: http://hgomersall.github.com/pyFFTW/
  license: BSD or GPL 2
  license_file: LICENSE.txt
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.

extra:
  recipe-maintainers:
    - grlee77
    - hgomersall
    - jakirkham
